const errors = [
  'FARANGO_CANT_OPEN_CONNECTION',
  'FARANGO_CANT_CREATE_DB',
  'FARANGO_CANT_USE_SPECIFIED_DB',
  'FARANGO_CANT_CREATE_COLLECTION',
  'FARANGO_CANT_GET_COLLECTION',
  'FARANGO_CANT_INSERT_DOC',
  'FARANGO_CANT_GET_DOC_BY_ID',
  'FARANGO_CANT_DROP_DB',
  'FARANGO_AQL_QUERY_FAILED',
]

export const ec = errors.reduce((codes, cur) => ({ ...codes, [cur]: cur }), {})
